#!/usr/bin/env bash

manifest_type="$1"

if [ -z "$manifest_type" ]; then
    echo "Usage: $0 <nginx|php>" >&2
    exit 1
fi

indent() {
    local expr='s/^/       /'

    if [ $(uname -s) = "Darwin" ]; then
        sed -l "$expr"
    else
        sed -u "$expr"
    fi
}

basedir="$( cd -P "$( dirname "$0" )" && pwd )"

source "$basedir/../conf/buildpack.conf"

if [ -z "$S3_BUCKET" ]; then
    echo "S3_BUCKET must be set" >&2
    exit 1
fi

# make a temp directory
tempdir="$( mktemp -t php_XXXX )"
rm -rf $tempdir
mkdir -p $tempdir
pushd $tempdir > /dev/null

echo "-----> Manifest for $manifest_type"

s3cmd ls "s3://$S3_BUCKET/package/" \
    | awk '{ print $4 }' \
    | sed "s/^s3:\/\/$S3_BUCKET\/package\///" \
    | grep "\.tgz$" \
    | grep "${manifest_type}" \
    | grep -v -e ".md5" \
    | sed -e "s/${manifest_type}-\([0-9.]*\)\\.tgz/\\1/" \
    | awk 'BEGIN {FS="."} {printf("%03d.%03d.%03d %s\n",$1,$2,$3,$0)}' \
    | sort -r \
    | cut -d" " -f2 \
    > manifest.${manifest_type}

cat "manifest.${manifest_type}" | indent

echo
echo "-----> Uploading manifest for ${manifest_type} to S3"

s3cmd put --acl-public --mime-type="text/plain" \
    manifest.${manifest_type} "s3://$S3_BUCKET" \
    | fold -w 70 | indent
