#!/usr/bin/env bash

set -e
set -o pipefail

basedir="$( cd -P "$( dirname "$0" )" && pwd )"
source "$basedir/../conf/buildpack.conf"

export PATH=${basedir}/../vendor/bin:$PATH

if [ -z "$S3_BUCKET" ]; then
    echo "Must set S3_BUCKET environment variable" >&2
    exit 1
fi

if [ -z "$TARGET_STACK" ]; then
    echo "TARGET_STACK must be set" >&2
    exit 1
fi

tempdir="$( mktemp -t libssh2_XXXX )"
rm -rf $tempdir
mkdir -p $tempdir
cd $tempdir

rm -rf /app/vendor/libssh2

libssh2_version=1.4.3

echo "-----> Downloading libssh2"

curl -L "http://www.libssh2.org/download/libssh2-${libssh2_version}.tar.gz" \
    | tar xzv

echo "-----> Compiling"

mkdir -p /app/vendor/libssh2
cd libssh2-${libssh2_version}
./configure --prefix=/app/vendor/libssh2 --with-openssl
make
make install

echo "-----> Building the archive"

pushd /app/vendor/libssh2

tar czf "${tempdir}/libssh2-${libssh2_version}.tgz" *

popd

s3cmd put \
    --verbose --acl-public \
    "$tempdir/libssh2-${libssh2_version}.tgz" \
    "s3://$S3_BUCKET/develop/$TARGET_STACK/package/libssh2-${libssh2_version}.tgz"

"$basedir/package-checksum" "libssh2-${libssh2_version}"
