#!/usr/bin/env bash

set -e
set -o pipefail

basedir="$( cd -P "$( dirname "$0" )" && pwd )"
source "$basedir/../conf/buildpack.conf"

export PATH=${basedir}/../vendor/bin:$PATH

if [ -z "$S3_BUCKET" ]; then
    echo "Must set S3_BUCKET environment variable" >&2
    exit 1
fi

if [ -z "$TARGET_STACK" ]; then
    echo "TARGET_STACK must be set" >&2
    exit 1
fi

tempdir="$( mktemp -t libmemcached_XXXX )"
rm -rf $tempdir
mkdir -p $tempdir
cd $tempdir

rm -rf /app/vendor/libmemcached

memcached_version=1.0.17

echo "-----> Downloading libmemcached"

curl -LO "https://launchpad.net/libmemcached/1.0/${memcached_version}/+download/libmemcached-${memcached_version}.tar.gz"
tar -xzvf "libmemcached-${memcached_version}.tar.gz"

echo "-----> Compiling"

cd libmemcached-${memcached_version}
mkdir -p /app/vendor/libmemcached
./configure --without-memcached --prefix=/app/vendor/libmemcached
make
make install

echo "-----> Building the archive"

pushd /app/vendor/libmemcached

tar czf "$tempdir/libmemcached-${memcached_version}.tgz" *

popd

s3_path=s3://$S3_BUCKET/develop/$TARGET_STACK/package/libmemcached-${memcached_version}.tgz

echo "-----> Uploading package to ${s3_path}"

s3cmd put --verbose \
    --acl-public \
    "$tempdir/libmemcached-${memcached_version}.tgz" \
    "${s3_path}"

"$basedir/package-checksum" libmemcached-${memcached_version}

echo "-----> Done building libmemcached package!"
