#!/usr/bin/env bash

set -e
set -o pipefail

mcrypt_version="$1"

if [ -z "$mcrypt_version" ]; then
    echo "Usage: $(basename "$0") VERSION" >&2
    exit 1
fi

basedir="$( cd -P "$( dirname "$0" )" && pwd )"
source "$basedir/../conf/buildpack.conf"

export PATH=${basedir}/../vendor/bin:$PATH

if [ -z "$S3_BUCKET" ]; then
    echo "Must set S3_BUCKET environment variable" >&2
    exit 1
fi

if [ -z "$TARGET_STACK" ]; then
    echo "TARGET_STACK must be set" >&2
    exit 1
fi

tempdir="$( mktemp -t libmcrypt_XXXX )"
rm -rf $tempdir
mkdir -p $tempdir
cd $tempdir

echo "-----> Downloading libmcrypt ${mcrypt_version}"
curl -L "http://sourceforge.net/projects/mcrypt/files/Libmcrypt/${mcrypt_version}/libmcrypt-${mcrypt_version}.tar.gz/download" \
    | tar xzv

echo "-----> Compiling"

mkdir -p /app/vendor/libmcrypt
cd libmcrypt-${mcrypt_version}
./configure --disable-posix-threads --prefix=/app/vendor/libmcrypt
make
make install

echo "-----> Building the archive"

pushd /app/vendor/libmcrypt

tar czf "${tempdir}/libmcrypt-${mcrypt_version}.tgz" *

popd

s3cmd put \
    --verbose --acl-public \
    "$tempdir/libmcrypt-${mcrypt_version}.tgz" \
    "s3://$S3_BUCKET/develop/$TARGET_STACK/package/libmcrypt-${mcrypt_version}.tgz"

"$basedir/package-checksum" "libmcrypt-${mcrypt_version}"
