#!/usr/bin/env bash

set -e
set -o pipefail

download_url="http://download.icu-project.org/files/icu4c/51.2/icu4c-51_2-src.tgz"

basedir="$( cd -P "$( dirname "$0" )" && pwd )"
source "$basedir/../conf/buildpack.conf"

export PATH=${basedir}/../vendor/bin:$PATH

if [ -z "$S3_BUCKET" ]; then
    echo "Must set S3_BUCKET environment variable" >&2
    exit 1
fi

tempdir="$( mktemp -t libicu_XXXX )"
rm -rf $tempdir
mkdir -p $tempdir
cd $tempdir

echo "-----> Downloading libicu"

curl -L "$download_url" | tar xzv

echo "-----> Compiling"

mkdir -p /app/vendor/libicu
cd icu
./source/runConfigureICU Linux --prefix=/app/vendor/libicu
make
make install

echo "-----> Building the archive"

pushd /app/vendor/libicu

tar czf "${tempdir}/libicu-51.tgz" *

popd

s3cmd put \
    --verbose --acl-public \
    "$tempdir/libicu-51.tgz" \
    "s3://$S3_BUCKET/package/libicu-51.tgz"

"$basedir/package-checksum" "libicu-51"
