#!/usr/bin/env bash

set -e

node_version="$1"

if [ -z "$node_version" ]; then
    echo "Usage: $(basename "$0") VERSION" >&2
    exit 1
fi

basedir="$( cd -P "$( dirname "$0" )" && pwd )"
source "$basedir/../conf/buildpack.conf"

if [ -z "$S3_BUCKET" ]; then
    echo "Must set S3_BUCKET environment variable" >&2
    exit 1
fi

tempdir="$( mktemp -t node_xxxx )"
rm -rf $tempdir
mkdir -p $tempdir
cd $tempdir

echo "-----> Downloading & building node ${node_version}"
# build and package nodejs
vulcan build -v \
  -n node \
  -c "cd node-v${node_version} && ./configure --prefix=/app/vendor/node && make install" \
  -p /app/vendor/node \
  -s http://nodejs.org/dist/v${node_version}/node-v${node_version}.tar.gz \
  --output "$tempdir/node-${node_version}.tgz" \


s3cmd put \
    --verbose --acl-public \
    "$tempdir/node-${node_version}.tgz" \
    "s3://$S3_BUCKET/package/node-${node_version}.tgz"

"$basedir/package-checksum" "node-${node_version}"
