#!/usr/bin/env bash

set -e

download_url="http://download.icu-project.org/files/icu4c/51.2/icu4c-51_2-src.tgz"

basedir="$( cd -P "$( dirname "$0" )" && pwd )"
source "$basedir/../conf/buildpack.conf"

export PATH=${basedir}/../vendor/bin:$PATH

if [ -z "$S3_BUCKET" ]; then
    echo "Must set S3_BUCKET environment variable" >&2
    exit 1
fi

tempdir="$( mktemp -t libmemcached_xxxx )"
rm -rf $tempdir
mkdir -p $tempdir
cd $tempdir

build_cmd=$(cat <<SH
    curl -L "$download_url" | tar xzv \
    && mkdir -p /app/vendor/libicu \
    && cd icu \
    && ./source/runConfigureICU Linux --prefix=/app/vendor/libicu \
    && make && make install
SH
)

vulcan build --verbose \
    --prefix /app/vendor/libicu \
    --source "." \
    --output "${tempdir}/libicu-51.tgz" \
    --name libicu \
    --command "$build_cmd"

s3cmd put \
    --verbose --acl-public \
    "$tempdir/libicu-51.tgz" \
    "s3://$S3_BUCKET/package/libicu-51.tgz"

"$basedir/package-checksum" "libicu-51"
