#!/usr/bin/env bash

set -e
set -o pipefail

basedir="$( cd -P "$( dirname "$0" )" && pwd )"
source "$basedir/../conf/buildpack.conf"

tempdir="$( mktemp -t composer_XXXX )"
rm -rf $tempdir
mkdir -p $tempdir
cd $tempdir

curl -L http://getcomposer.org/composer.phar > composer.phar
if hash md5sum 2>/dev/null; then
    md5sum composer.phar > composer.phar.md5
else
    md5 -r composer.phar > composer.phar.md5
fi

s3cmd put --verbose --acl-public \
    ./composer.phar s3://$S3_BUCKET/composer/composer.phar

s3cmd put --verbose --acl-public \
    ./composer.phar.md5 s3://$S3_BUCKET/composer/composer.phar.md5
