#!/bin/bash

BUILD_DIR="$2"
basedir="$( cd -P "$( dirname "$0" )" && pwd )"
source $basedir/../bin/common.sh

function requires_cakephp2() {
    [ $(jq --raw-output '.require["pear-pear.cakephp.org/CakePHP"]' < "$BUILD_DIR/composer.json") != "null" ]
}

function sets_framework_cakephp2() {
    [ $(jq --raw-output '.extra.heroku.framework' < "$BUILD_DIR/composer.json") == "cakephp2" ]
}

case "$1" in
    detect)
        if [ ! -f "$BUILD_DIR/composer.json" ]; then
            exit 1
        fi

        if requires_cakephp2 || sets_framework_cakephp2; then
            echo "-----> Detected CakePHP2 App"
            exit 0
        else
            exit 1
        fi
        ;;
    compile)
        echo "-----> Setting up CakePHP2 app"
        cp "$basedir/../conf/nginx/cakephp2.conf.erb" "$BUILD_DIR/conf/site.conf.erb"
        ;;
esac
