#!/bin/bash

BUILD_DIR="$2"
basedir="$( cd -P "$( dirname "$0" )" && pwd )"

case "$1" in
detect)
    exit 1
    ;;
compile)
    echo "-----> Setting up default configuration"
    cp "$basedir/../conf/nginx/default_site.conf.erb" "$BUILD_DIR/conf/site.conf.erb"
    ;;
esac
