#!/bin/bash

BUILD_DIR="$2"
basedir="$( cd -P "$( dirname "$0" )" && pwd )"

function requires_slim() {
    jq --raw-output '.packages | .[] | .name' < "$BUILD_DIR/composer.lock" | grep -q '^slim/slim$'
}

function sets_framework_slim() {
    [ $(jq --raw-output '.extra.heroku.framework' < "$BUILD_DIR/composer.json") == "slim" ]
}

case "$1" in
    detect)
        if [ ! -f "$BUILD_DIR/composer.json" ]; then
            exit 1
        fi

        if requires_slim || sets_framework_slim; then
            echo "-----> Detected Slim app"
            exit 0
        else
            exit 1
        fi
        ;;
    compile)
        echo "-----> Setting up Slim app"
        cp "$basedir/../conf/nginx/slim.conf.erb" "$BUILD_DIR/conf/site.conf.erb"
        ;;
esac
