#!/bin/bash

BUILD_DIR="$2"
basedir="$( cd -P "$( dirname "$0" )" && pwd )"
source $basedir/../bin/common.sh

function requires_symfony2() {
    jq --raw-output '.packages | .[] | .name' < "$BUILD_DIR/composer.lock" | grep -q '^symfony/symfony$'
}

function sets_framework_symfony2() {
    [ $(jq --raw-output '.extra.heroku.framework' < "$BUILD_DIR/composer.json") == "symfony2" ]
}

case "$1" in
    detect)
        if [ ! -f "$BUILD_DIR/composer.json" ]; then
            exit 1
        fi

        if requires_symfony2 || sets_framework_symfony2; then
            echo "-----> Detected Symfony2 App"
            exit 0
        else
            exit 1
        fi
        ;;
    get-log-files)
        if [ ! -d "var/logs" ]; then
            echo "var/logs/prod.log" "var/logs/dev.log"
        else
            echo "app/logs/prod.log" "app/logs/dev.log"
        fi
        ;;
    compile)
        echo "-----> Setting up Symfony2 app"
        cp "$basedir/../conf/nginx/symfony2.conf.erb" "$BUILD_DIR/conf/site.conf.erb"
        ;;
    end)
        BUILD_DIR="$1"
        CACHE_DIR="$2"
        APP_DIR="/app"

        APP_CACHE_DIR="app/cache"
        BIN_CONSOLE="app/console"

        if [ -d "var/cache" ]; then
            APP_CACHE_DIR="var/cache"
        fi

        if [ -f "bin/console" ]; then
            BIN_CONSOLE="bin/console"
        fi

        status "Warmuping cache"
        rm -rf $APP_CACHE_DIR/*
        php $BIN_CONSOLE cache:warmup --env=prod --no-debug | indent


        status "In-place replacment of $CACHE_DIR to $APP_DIR"
        find $CACHE_DIR/$APP_CACHE_DIR/prod -type f -exec sed -i "s@$CACHE_DIR@$APP_DIR@g" {} \; | indent
        grep $CACHE_DIR/$APP_CACHE_DIR/prod -r . && error "Could find some '$CACHE_DIR' :/ "

        status "End"
        ;;
esac
