#!/bin/bash

BUILD_DIR="$2"
basedir="$( cd -P "$( dirname "$0" )" && pwd )"
source $basedir/../bin/common.sh

function requires_symfony2() {
    jq --raw-output '.packages | .[] | .name' < "$BUILD_DIR/composer.lock" | grep -q '^symfony/symfony$'
}

function sets_framework_symfony2() {
    [ $(jq --raw-output '.extra.heroku.framework' < "$BUILD_DIR/composer.json") == "symfony2" ]
}

case "$1" in
    detect)
        if [ ! -f "$BUILD_DIR/composer.json" ]; then
            exit 1
        fi

        if requires_symfony2 || sets_framework_symfony2; then
            echo "-----> Detected Symfony2 App"
            exit 0
        else
            exit 1
        fi
        ;;
    get-log-files)
        echo "app/logs/prod.log" "app/logs/dev.log"
        ;;
    compile)
        echo "-----> Setting up Symfony2 app"
        cp "$basedir/../conf/nginx/symfony2.conf.erb" "$BUILD_DIR/conf/site.conf.erb"
        ;;
    end)
        BUILD_DIR="$1"
        CACHE_DIR="$2"
        APP_DIR="/app"

        status "Warmuping cache"
        rm -rf app/cache/*
        php app/console cache:warmup --env=prod --no-debug | indent


        status "Inplace replacment of $CACHE_DIR to $APP_DIR"
        find $CACHE_DIR/app/cache/prod -type f -exec sed -i "s@$CACHE_DIR@$APP_DIR@g" {} \; | indent
        grep $CACHE_DIR/app/cache/prod -r . && error "Could find some '$CACHE_DIR' :/ "

        status "End"
        ;;
esac
