#!/bin/bash

BUILD_DIR="$2"
basedir="$( cd -P "$( dirname "$0" )" && pwd )"

function requires_zf2() {
    jq --raw-output '.packages | .[] | .name' < "$BUILD_DIR/composer.lock" | grep -q '^zendframework/zendframework$'
}

function sets_framework_zf2() {
    [ $(jq --raw-output '.extra.heroku.framework' < "$BUILD_DIR/composer.json") == "zf2" ]
}

case "$1" in
    detect)
        if [ ! -f "$BUILD_DIR/composer.json" ]; then
            exit 1
        fi

        if requires_zf2 || sets_framework_zf2; then
            echo "-----> Detected Zend2 app"
            exit 0
        else
            exit 1
        fi
        ;;
    compile)
        echo "-----> Setting up Zend2 app"
        cp "$basedir/../conf/nginx/zf2.conf.erb" "$BUILD_DIR/conf/site.conf.erb"
        ;;
esac
