#!/usr/bin/env bash

igbinary_version="1.1.1"

curl -L "https://github.com/igbinary/igbinary/archive/${igbinary_version}.tar.gz" \
    | tar xzv

cd "igbinary-${igbinary_version}"
/app/vendor/php/bin/phpize
./configure --with-php-config=/app/vendor/php/bin/php-config \
            --enable-igbinary

make
cp modules/igbinary.so "$EXT_DIR/igbinary.so"
echo "extension=igbinary.so" > "$PREFIX/etc/conf.d/igbinary.ini"
