#!/usr/bin/env bash

set -e
set -o pipefail

ssh2_version=0.12
libssh2_version=1.4.3

mkdir -p /app/vendor/libssh2
curl "${S3_URL}/package/libssh2-${libssh2_version=1.4.3}.tgz" | tar xzv -C /app/vendor/libssh2

curl -L "http://pecl.php.net/get/ssh2-${ssh2_version}.tgz" \
    | tar xzv

cd ssh2-${ssh2_version}
/app/vendor/php/bin/phpize
./configure --with-php-config=/app/vendor/php/bin/php-config \
    --with-ssh2=/app/vendor/libssh2 \

make
cp modules/ssh2.so "$EXT_DIR/ssh2.so"
echo "extension=ssh2.so" > "$CONF_DIR/ssh2.ini"
